favicon: null
name: Ramjee Chandran
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7007169
  brandStrength: 0.5107919329311699
  lightness: 0.5125448
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  rhythmicContrast: 0.8422939
typography_spectrum: 0.01517978380434215
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.1654420103877783
analytics:
  twitter: null
  google: null
  facebook: null
